### PR TITLE
Legend of the Galactic Heroes (SubsPlease)

### PR DESCRIPTION
**Pull request by Zotikus1001**
SubsPlease releases.

### CODE REVIEW

**Comment by paulo27ms** [comment]
You need to fill all the IDs.

**Comment by Zotikus1001** [comment]
I did fill all the id's, Anilist just has it listed differently, thus why I made a separate redirect only for anilist.

**Comment by paulo27ms** [comment]
That won't work. You need to use "?|?|20628" for example. Taiga has no idea what ID it is if you don't include all.

**Comment by Zotikus1001** [comment]
I see. Good to know. Fix applied.

**Pull request merged**
