### PR TITLE
Add "Mushoku Tensei: Isekai Ittara Honki Dasu Part 2/2nd Season"

### PR DESCRIPTION
**Pull request by lukas-berger**

### CODE REVIEW

**Comment by lukas-berger** [comment]
Sorry, doesn't appear to be working.

**Comment by paulo27ms** [comment]
This seems fine, what's the issue?

**Comment by flat34** [comment]
I got it to correctly recognize the [SubsPlease] release and some others by adding just "Mushoku Tensei" to the alternative titles field of _both_ seasons, in conjunction with lukas' commit.

**Comment by lukas-berger** [comment]
> I got it to correctly recognize the [SubsPlease] release and some others by adding just "Mushoku Tensei" to the alternative titles field of _both_ seasons, in conjunction with lukas' commit.

Yeah, I checked the following combinations of the alternative title (Mushoku Tensei) with the [SubsPlease] release:
on neither season: detected as episode 12 of S2
on just S1: **detected as episode 1 of S2**
on just S2: detected as episode 12 of S2
on both S1 and S2: **detected as episode 1 of S2**

@paulo27ms 
Either way, without adding an alternative title, it wouldn't work correctly, hence why I removed my pull request.

**Comment by paulo27ms** [comment]
It's not meant to work if the titles aren't set correctly so the issue was not this change as that has nothing to do with it.

**Comment by erengy** [comment]
I just merged #88 because it had episode counts too. But still, thanks, @lukas-berger.

**Pull request closed without merging**
