### PR TITLE
Update Two Gintama Entries

### PR DESCRIPTION
**Pull request by mnabid**
- ***Gintama.: Shirogane no Tamashii-hen*** is [split cour](https://myanimelist.net/anime/37491/Gintama__Shirogane_no_Tamashii-hen_-_Kouhan-sen) (12 + 14). So, `Ep 13-26 (first cour) -> Ep 1-14 (second cour)`.
Mini encoder groups like Judas ~~and Kayoanime~~ have all 26 episodes together.

 - Added ***Gintama: The Semi-Final*** as well.

### CODE REVIEW

**Comment by paulo27ms** [comment]
Is this new line really necessary?
- 36838|14095|100784:354-367 -> 37491|41079|101925:1-14
Should already be handled by 
- 918|818|918:354-367 -> 37491|41079|101925:1-14!

**Comment by erengy** [comment]
Hey @mnabid, thanks for the PR.

The first rule works for Judas, which is currently the most popular release on Nyaa. Should be merged, I think.

The second rule doesn't seem to be necessary, as @paulo27ms noted.

I couldn't find any releases that require the rule for *The Semi-Final* either. Did I miss some, or was the rule added as a precaution?

**Comment by mnabid** [comment]
@paulo27ms Sorry for the late reply, I was away from home.

> Is this new line really necessary?

Pretty sure it is, if I understood the [README](https://github.com/erengy/anime-relations#example) correctly.

```
Gintama/
├── (...)
├── Episode 342-353
├── Episode 354-367
└── (...)
```

This scenario should be covered by the [exisiting rules](https://github.com/erengy/anime-relations/blob/eebafc8fdcd47d8d6e1a2b24e53e08e5c778e95c/anime-relations.txt#L355-L358) you mentioned. But it wouldn't work in the following case:

```
Gintama.: Shirogane no Tamashii-hen/
├── Episode 342-353
├── Episode 354-367
```

This is where the [new line](https://github.com/erengy/anime-relations/blob/eebafc8fdcd47d8d6e1a2b24e53e08e5c778e95c/anime-relations.txt#L361) comes into play. (I actually copy-pasted this rule from *AoT Season 3 Part 2*)

https://github.com/erengy/anime-relations/blob/eebafc8fdcd47d8d6e1a2b24e53e08e5c778e95c/anime-relations.txt#L823-L827

**Comment by mnabid** [comment]
@erengy
>I couldn't find any releases that require the rule for The Semi-Final either. Did I miss some, or was the rule added as a precaution?

Precaution.
[Gintama wiki](https://gintama.fandom.com/wiki/Episode_368) and [filler list](https://www.animefillerlist.com/shows/gintama) listed these two episodes as 368-369.

**Comment by paulo27ms** [comment]
I suppose it is fine, it's just that in those cases you could just set an alternative title for that entry and it'd apply the already existing rule. Didn't realize AoT had it too.
The extra rule shouldn't cause any conflict anyway I guess.

**Comment by mnabid** [comment]
@erengy

**Comment by mnabid** [comment]
Hi @erengy, it's been quite a long time. Would you mind reviewing it again?
[I replied about the relevance of the 2nd and 3rd rule.](https://github.com/erengy/anime-relations/pull/85#issuecomment-934251085) Let me know if I need to make any changes.

**Comment by erengy** [comment]
Hey @mnabid, thanks for the explanations.

I spent another hour contemplating this, but in the end, decided against adding the latter two rules. You're right about that case, but I think we should work with existing releases rather than trying to cover every possible scenario.

I'll merge the first rule after removing the `!`, otherwise it could redirect episodes 13-14 back to 1-2 (because source and destination ranges are overlapping).

**Pull request merged**
