### PR TITLE
Boku no Hero Academia remove incorrect reverse rule

### PR DESCRIPTION
**Pull request by lolamtisch**
This is incorrect. Because season 1 has 13 episodes and season 2 has 25, this results in that episode 14 gets recognized as ep 1 again in season 2. Removing the reverse rule fixes that.

https://myanimelist.net/anime/31964/Boku_no_Hero_Academia
https://myanimelist.net/anime/33486/Boku_no_Hero_Academia_2nd_Season

### CODE REVIEW

**Comment by paulo27ms** [comment]
This rule is like that because sometimes you'll have groups that use "S2 - 14" for the first episode of season 2 while some groups will use "S2 - 14" for the fourteenth episode of season 2. 
With your edit you fix issue where it gets confused but it breaks recognition for the second case.
There's no real fix for this outside of Taiga asking which episode it really is when you start watching.
Any series that has more episodes in the second season than in the first has this issue.

**Comment by lolamtisch** [comment]
Yeah, one of the cases will always break here. But in my opinion it is worse to change the episodes to a wrong number than not changing them at all and it is less confusing for the user.

**Comment by paulo27ms** [comment]
Ultimately, it's best to support the option that's more inclusive (i.e. it can have a wrong episode but everything else will work while if we remove it we're removing support for a bunch of groups entirely).
There's not much impact because it'll just skip that episode and not necessarily mess up your episode count.
But I don't know how many groups actually use that naming scheme, maybe if you wanna do that research and share, it could be an argument to remove it.

**Comment by lolamtisch** [comment]
https://animetosho.org/episode/boku-no-hero-academia-2017-25.190147
The naming is probably split at 50%. 

The Problem is that I use anime-relations in my streaming page tracking extension. Where probably around 90% of the pages use the 1-25 naming schema. The other 10% can fix it by setting an episode offset manually, if this rule is fixed. Currently it is just confusing for the user that it jumps to the wrong episode number mid season and setting an offset on an offset is confusing.

But I understand that is my Problem, but I still see it conceptually as a wrong rule. 

If that is really the official view of erengy on entries with more episodes on the second season then the first, then I can probably filter it out on my side somehow.

**Comment by erengy** [comment]
Adding `!` to rules for TV series is generally a good idea, because:

1. It handles the cases @paulo27ms mentioned above.
2. It handles some cases with Taiga users messing up alternative titles.

This is indeed a tradeoff and I'm not sure what's best in this case. I'll go ahead and accept the change for now.

**Pull request merged**
