### PR TITLE
Add Enmusubi no Youko-chan S2 and S3

### PR DESCRIPTION
**Pull request by AthabaWolfssturm**
Enmusubi no Youko-chan (Huyao Xiao Hongniang) 14-27 -> ~: Wangquan Fugui 1-14

Enmusubi no Youko-chan (Huyao Xiao Hongniang) 28-40 -> ~: Yue Hong 1-13

HorribleSubs lists them all as "Enmusubi no Youko-chan" with continuing episode numbers, while MAL and Kitsu differentiate between the three seasons and use the original Chinese name.

### CODE REVIEW

**Comment by wopian** [comment]
The Japanese broadcast is quite different with episodes reordered & missing/new scenes. Its a separate show on Kitsu.

I.e Episode 13 is the start of Season 3 of the original chinese version.

**Comment by AthabaWolfssturm** [comment]
Oh wow, that's convoluted.
But MAL only has the Chinese series edited to fit the Japanese release, right?

**Comment by wopian** [comment]
MAL just has the Chinese series with the old episode discussion threads bumped (so they're technically discussing different episodes than the original 2015 threads 😆)

**Comment by AthabaWolfssturm** [comment]
But this should work for MAL at least, right?

**Comment by AthabaWolfssturm** [comment]
Closing this as I'm too confused as to what entry where is the actual thing that's currently airing.
Sorry for my hastiness.

**Pull request closed without merging**
