### PR TITLE
Add High School DxD Hero: Taiikukan-ura no Holy

### PR DESCRIPTION
**Pull request by xChickens**

### CODE REVIEW

**Comment by erengy** [comment]
Thanks, but there are a few issues with this one:

- You should update the `last_modified` date too.
- You should replace `97767` with `?`.

Also note that this rule will not work until *High School DxD Hero* starts airing, because Taiga totally ignores not-yet-aired anime in its identification process (it probably shouldn't in this case).

**Comment by ShaunV2** [comment]
@erengy [High School DxD Hero](https://kitsu.io/anime/high-school-dxd-hero) is already airing since April 10th, 2018 and [Episode 0](https://kitsu.io/anime/high-school-dxd--hero-taiikukan-ura-no-holy) already finished airing.

It looks like this time Crunchyroll does not have the streaming rights for the 4th season.

**Comment by erengy** [comment]
The episode that was aired on April 10th is the Episode 0. The TV series will start airing on April 17th.

Kitsu should update their database by either changing the start date of the series, or merging the two entries.

**Comment by wopian** [comment]
@erengy no, I just forgot to update the start date when episode 0 was added

**Comment by erengy** [comment]
@wopian Yeah, I imagined that was the case. What I meant is that a new entry for Episode 0 was added, but the main entry seemed to include it as well. Apparently it confused some Kitsu users too.

**Comment by xChickens** [comment]
Whoops, my bad. I was in a rush when I was editing it. Also, didn't know that the same series number should be put for AniList if it doesn't exist, so thanks for the notice.

**Pull request merged**
