### PR TITLE
Add "Mushoku Tensei II: Isekai Ittara Honki Dasu"

### PR DESCRIPTION
**Pull request by sitiom**
Note: AniList entry combines Episode 0 / Shugo Jutsushi Fitz. Not sure how to handle that

### CODE REVIEW

**Comment by cynide4869** [comment]
Since it's only Anilist that's following that, then perhaps a separate entry just for Anilist to map 0-12 -> 1-13. Not sure if that would work though, will give it a try

**Comment by sitiom** [comment]
> Since it's only Anilist that's following that, then perhaps a separate entry just for Anilist to map 0-12 -> 1-13, something like a self-map. Not sure if that would work though, will give it a try

I've tried it, and it only works for episode 0. Anything after episode 1 does not offset itself.

**Comment by cynide4869** [comment]
@sitiom That's a bummer. Wonder how this could be fixed then, will have to rename the file each time.

**Comment by sitiom** [comment]
#156

**Pull request closed without merging**
